name = "juranyi-backend"
main = "src/index.js"
compatibility_date = "2024-09-23"

# Se llena automáticamente al correr `npx wrangler d1 create juranyi-db`
# (copia el database_id que te da ese comando aquí abajo).
[[d1_databases]]
binding = "DB"
database_name = "juranyi-db"
database_id = "0ea4a52b-1f2c-45be-881e-5314655b838f"
