name = "juranyi-backend"
main = "src/index.js"
compatibility_date = "2024-09-23"

# Se llena automáticamente al correr `npx wrangler d1 create juranyi-db`
# (copia el database_id que te da ese comando aquí abajo).
[[d1_databases]]
binding = "DB"
database_name = "juranyi-db"
database_id = "PON-AQUI-EL-DATABASE-ID-QUE-TE-DIO-WRANGLER"
